graduationProject/Controllers/RolesController.cs
using graduationProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static graduationProject.Helper;

namespace graduationProject.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        //when i use await youshoud use async
        public async Task<IActionResult> Index()
        {
            //to list all role
            return View(await _roleManager.Roles.ToListAsync());
        }
        //to add new role and use  role view model
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(RoleFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                //check if model exit in database or not
                if (await _roleManager.RoleExistsAsync(model.Name))
                {
                    ModelState.AddModelError("Name", "Role is exits!");
                    return View("Index", await _roleManager.Roles.ToListAsync());
                }
                else
                {
                    //save new role in role table
                    await _roleManager.CreateAsync(new IdentityRole(model.Name.Trim()));
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                //return view with the same data if model not valid
                return View("Index", await _roleManager.Roles.ToListAsync());
            }
        }
        [NoDirectAccess]
        public async Task<IActionResult> Edit(string id)
        {
            //هجيب المستخدم بي الاى دى بتاعه
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IdentityRole model)
        {
            if (ModelState.IsValid)
            {
                var rolelist = await _roleManager.FindByNameAsync(model.Name);
                if (rolelist != null)
                {
                    //return Json($"Email {model.Name} is already in use.");
                    ModelState.AddModelError("Name", $"Email {model.Name} is already in use.");
                    return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });

                }
                //هو هيجيب المستخدم ويشوفه موجود ولا لا
                var role = await _roleManager.FindByIdAsync(model.Id);
                if (role == null)
                {
                    return NotFound();
                }
                role.Name = model.Name;
                await _roleManager.UpdateAsync(role);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAllRole", await _roleManager.Roles.ToListAsync())});

            }
            else
            {
                ModelState.AddModelError("", "You have to fill all the required fields");
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", model) });

            }
        }
        /*******Role Name Validation**********/
        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> RoleName(IdentityRole model)
        {
            var role = await _roleManager.FindByNameAsync(model.Name);
            if (role != null)
            {
                return Json($"Roles {model.Name} is already in use.");
            }

            return Json(true);
        }



    }
}

graduationProject/Controllers/UsersController.cs
using graduationProject.Models;
using graduationProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static graduationProject.Helper;

namespace graduationProject.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            //to get all user with his role
            var users = await _userManager.Users.Where(u => u.status == 1).Select(user => new UserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                UserName = user.UserName,
                Email = user.Email,
                Roles = _userManager.GetRolesAsync(user).Result //to get all roles to that user
            }).ToListAsync();
            return View(users);
        }
        //to manage roles for users
        [NoDirectAccess]
        public async Task<IActionResult> ManageRoles(string id)
        {
            //to check if user exit or not
            var user = await _userManager.FindByIdAsync(id);
            if(user == null)
            {
                return NotFound();
            }
            else
            {
                var roles = await _roleManager.Roles.ToListAsync();
                var viewModel = new UserRolesViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    Roles = roles.Select(role => new RoleViewModel
                    {
                        RoleId = role.Id,
                        RoleName = role.Name,
                        IsSelected = _userManager.IsInRoleAsync(user, role.Name).Result
                    }).ToList()
                };
                return View(viewModel);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRoles(UserRolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                //هشوف هل فى مستخدم ولا لا 
                var user = await _userManager.FindByIdAsync(model.UserId);
                if (user == null)
                {
                    return NotFound();
                }
                //هيجيب كل ال الرول اللى تخص المستخدم دا
                var userRoles = await _userManager.GetRolesAsync(user);
                //همشي على كل واحده من الورل اللى جوا المودل اللى جايه من الصفحه واقارنها بالموجود
                foreach (var role in model.Roles)
                {
                    //هشوف هيا موجوده ومتعلم عليها ولا لا وكذلك موجوده ومش متعلم ولا لا
                    if (userRoles.Any(r => r == role.RoleName) && !role.IsSelected)
                    {
                        await _userManager.RemoveFromRoleAsync(user, role.RoleName);
                    }
                    if (!userRoles.Any(r => r == role.RoleName) && role.IsSelected)
                    {
                        await _userManager.AddToRoleAsync(user, role.RoleName);
                    }
                }
                ///get all users
                var users = await _userManager.Users.Select(user => new UserViewModel
                {
                    Id = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Email = user.Email,
                    Roles = _userManager.GetRolesAsync(user).Result //to get all roles to that user
                }).ToListAsync();
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAllUser", users) });

            }
            else
            {
                ModelState.AddModelError("", "You have to fill all the required fields");
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "EditProfile", model) });

            }


        }

        //to create new user
        //public async Task<IActionResult> Add()
        //{
        //    //هجيب كل الرول من جدول الرول بس تيجي ايدي واسم وبس
        //    var roles = await _roleManager.Roles.
        //        Select(r => new RoleViewModel {
        //            RoleId =r.Id,
        //            RoleName = r.Name
        //            }).ToListAsync();
        //    var viewModel = new AddUserViewModel
        //    {
        //        Roles = roles
        //    };
        //    return View(viewModel);
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Add(AddUserViewModel model)
        //{
        //    //هيفحص هل المودل اللى جاى فيه داتا ولا لا
        //    if (ModelState.IsValid)
        //    {
        //        //هيشوف هو على الاقل اختار رول واحده ولا لا
        //        if(!model.Roles.Any(r => r.IsSelected))
        //        {
        //            ModelState.AddModelError("Roles", "Please Select At Least one Role");
        //            return View(model);
        //        }
        //        //هيشوف هل الايميل واليوزرنيم موجودين قبل كدا ولا لا
        //        if (await _userManager.FindByEmailAsync(model.Email)!=null)
        //        {
        //            ModelState.AddModelError("Email", "Email is Aleardy Exit");
        //            return View(model);
        //        }
        //        if (await _userManager.FindByNameAsync(model.UserName) != null)
        //        {
        //            ModelState.AddModelError("UserName", "UserName is Aleardy Exit");
        //            return View(model);
        //        }
        //        //هنا بقي ابدا اخزنها فى الداتا بيز بتاعت المستخدم هعمل اوبجكت
        //        var user = new ApplicationUser
        //        {
        //            UserName = model.UserName,
        //            Email = model.Email,
        //            FirstName = model.FirstName,
        //            LastName = model.LastName,
        //            FullName = model.FirstName + model.LastName
        //        };
        //        var result = await _userManager.CreateAsync(user, model.Password);
        //        //هشوف هل تم تخزينه فعلا ولا لا 
        //        if (!result.Succeeded)
        //        {
        //            //هدور على الايرور فين 
        //            foreach (var error in result.Errors)
        //            {
        //                //هحطها فى الرول عشان اخر حاجه تحت وتبان 
        //                ModelState.AddModelError("Roles", error.Description);
        //            }
        //            return View(model);
        //        }
        //        //هنا بقي طالما نجح التسجيل يبقي اضيفه فى جدول الرول واستخدم 
        //        //واراعي حتت السليكت عشان ياخد اللى اتحددت بس مش كلهم
        //        await _userManager.AddToRolesAsync(user, model.Roles.Where(r => r.IsSelected).Select(r=>r.RoleName));
        //        return RedirectToAction(nameof(Index));

        //    }
        //    else
        //    {
        //        return View(model);
        //    }
        //}
        // جزء تعديل الصفحه الشخصية للمستخدم
        [NoDirectAccess]
        public async Task<IActionResult> EditProfile(string id)
        {
            //هجيب المستخدم بي الاى دى بتاعه
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            else
            {
                var viewModel = new ProfileViewModel
                {
                    Id = id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Email = user.Email,
                    UserName = user.UserName
                };
                return View(viewModel);
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfile(ProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                //هو هيجيب المستخدم ويشوفه موجود ولا لا
                var user = await _userManager.FindByIdAsync(model.Id);
                if(user == null)
                {
                    return NotFound();
                }
                //هيشوف بي الاي دى هيجيب الايميل موجود ولا لا
                var userWithSameEmail = await _userManager.FindByEmailAsync(model.Email);
                if(userWithSameEmail != null && userWithSameEmail.Id != model.Id)
                {
                    ModelState.AddModelError("Email", "email is aleardy exit");
                    //return View(model);
                    return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "EditProfile", model) });

                }
                //هيشوف اليوزر نيم موجود قبل كدا ولا لا
                var userWithSameUsername = await _userManager.FindByNameAsync(model.UserName);
                if(userWithSameUsername!=null && userWithSameUsername.Id != model.Id)
                {
                    ModelState.AddModelError("UserName", "UserName is aleardy exit");
                    //return View(model);
                    return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "EditProfile", model) });

                }
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;

graduationProject/Views/Shared/_DashbordLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - graduationProject</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/dashboard/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    <!------fonts------->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa&family=Vibes&display=swap" rel="stylesheet">
    <style>
        main {
            padding: 15px;
            padding-top: 50px;
        }
        body {
            background-color: #f4f3ef;
        }
    </style>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Care To Day</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            
        </form>
        <partial name="_LoginAdminPartial" />
        
        <!-- Navbar-->

    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Manage</div>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link @ViewBag.dashboard" asp-action="Dashboard" asp-controller="Home">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Dashboard
                                </a>
                                <a class="nav-link @ViewBag.profile" asp-area="Identity" asp-page="/Account/Manage/Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Profile
                                </a>
                                <a class="nav-link @ViewBag.user" asp-action="Index" asp-controller="Users">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Users
                                </a>
                                <a class="nav-link @ViewBag.roles" asp-action="Index" asp-controller="Roles">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Roles
                                </a>
                                <a class="nav-link @ViewBag.governorate" asp-action="Index" asp-controller="Governorate">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    governorate
                                </a>
                                <a class="nav-link @ViewBag.department" asp-action="Index" asp-controller="Department">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    department
                                </a>
                                <a class="nav-link @ViewBag.hospitallist" asp-action="Index" asp-controller="Hospital">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Hospitals List
                                </a>

                                <a class="nav-link @ViewBag.usersreserve" asp-action="GetAllUserReserve" asp-controller="Hospital">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    All User Reservation
                                </a>

                                <a class="nav-link @ViewBag.usergrouphospital" asp-action="GetUserGroupByHospital" asp-controller="Hospital">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Hospitals Reservation
                                </a>

                                <a class="nav-link @ViewBag.Oxeginlist" asp-action="Index" asp-controller="OxygenTube">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Oxygen tubes
                                </a>
                                <a class="nav-link @ViewBag.usersreservetubes" asp-action="GetAllUserReserve" asp-controller="OxygenTube">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    All User Reservation
                                </a>
                                <a class="nav-link @ViewBag.usergrouptubes" asp-action="GetUserGroupByTube" asp-controller="OxygenTube">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    oxygen Reservation
                                </a>
                            }
                            <!------- for hospital admin-------->
                            if (User.IsInRole("HospitalAdmin"))
                            {
                                <a class="nav-link @ViewBag.dashboard" asp-action="Index" asp-controller="Home">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Dashboard
                                </a>
                                <a class="nav-link @ViewBag.profile" asp-area="Identity" asp-page="/Account/Manage/Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Profile
                                </a>
                                <a class="nav-link @ViewBag.hospitalbypulisher" asp-action="GetHospitalByPublisher" asp-controller="Hospital">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Hospital
                                </a>

                                <a class="nav-link @ViewBag.UserByHospital" asp-action="GetUserByHospital" asp-controller="Hospital">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Hospital Reservation
                                </a>
                            }
                            <!------- for oxegin admin-------->
                            if (User.IsInRole("OxginAdmin"))
                            {
                                <a class="nav-link @ViewBag.dashboard" asp-action="Index" asp-controller="Home">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Dashboard
                                </a>
                                <a class="nav-link @ViewBag.profile" asp-area="Identity" asp-page="/Account/Manage/Index">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Profile
                                </a>
                                <a class="nav-link @ViewBag.tubebypulisher" asp-action="GetTubeByPublisher" asp-controller="OxygenTube">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Oxgin Tubes
                                </a>

                                <a class="nav-link @ViewBag.UserBytube" asp-action="GetUserByTube" asp-controller="OxygenTube">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Oxgin Reservation
                                </a>
                            }
                        }

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <!-- Modal -->
            <div class="modal fade" id="form-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content" @*style="margin-top:15%"*@>
                        <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel"></h5>
                            <button type="button" class="btn-close bt" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary bt" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="loaderbody" id="loaderbody">
                <div class="loader"></div>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>*@
    <!--هنا عشان الجافا اسكريب والفانكشن بتاع الموقع نفسه-->
    <script src="/dashboard/js/scripts.js"></script>
    <!--دول عشان الاشكال-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/dashboard/assets/demo/chart-area-demo.js"></script>
    <script src="~/dashboard/assets/demo/chart-bar-demo.js"></script>
    <!--دول عشان الجداول بي الاكشن والسيرش بتاعهم-->
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/dashboard/js/datatables-simple-demo.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notify.min.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

graduationProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - graduationProject</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="~/css/site.css" />

    <!------fonts------->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa&family=Vibes&display=swap" rel="stylesheet">

</head>
<body>
    <header style="direction: rtl;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container hadanat-container-home">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Care To Day</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">الصفحة الرئيسية</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#aboutus">من نحن</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  href="#contactus">تواصل معنا</a>
                        </li>
                    </ul>
                    @*<partial name="_LoginUserPartial" />*@
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    @*<div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@
    @RenderBody()
    <!-- Modal -->
    <div class="modal fade" id="form-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content" @*style="margin-top:15%"*@>
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel"></h5>
                    <button type="button" class="btn-close bt" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary bt" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    @*<div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>*@
    <footer class="border-top footer text-muted">
        <div class="container">
            <p style="text-align:center;" جميع الحقوق محفوظة Care To Day 2021©"><span style="display:inline-block;">جميع الحقوق محفوظة <br></span>Care To Day 2021&copy; </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notify.min.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>