graduationProject/Models/Hospital.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace graduationProject.Models
{
    public class Hospital
    {
        [Key]
        public int Hos_Id { get; set; }
        [Display(Name = "اسم المستشفي")]
        public string Hos_Name { get; set; }
        [Display(Name = "عدد الحضانات")]
        public int Hos_Incubators { get; set; }
        [Display(Name = "سعر اليوم")]
        public float DayPrice { get; set; }
        [Display(Name = "العنوان")]
        public string Hos_Location { get; set; }
        [Display(Name = "رقم التليفون")]
        public string Hos_Phone { get; set; }
        [Display(Name = "صورة المستشفي")]
        public string Hos_Image { get; set; }

        [Display(Name = "تاريخ التسجيل")]
        public DateTime dateCreate { get; set; }
        [Display(Name = "صورة المستشفي")]
        public byte[] hos_pic { get; set; }

        [ForeignKey("Department")]
        public int Dept_Id { get; set; }
        public Department Department { get; set; }

        [ForeignKey("User")]
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

    }
}

graduationProject/ViewModels/HospitalViewModel.cs
using graduationProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace graduationProject.ViewModels
{
    public class HospitalViewModel
    {
        public string Hos_Name { get; set; }
        public IEnumerable<UserReservation> userResverations { get; set; }
    }
}

graduationProject/Controllers/HospitalController.cs
using graduationProject.Models;
using graduationProject.Repositories;
using graduationProject.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;

using static graduationProject.Helper;
using Microsoft.AspNetCore.Authorization;

namespace graduationProject.Controllers
{
    
    public class HospitalController : Controller
    {
        private readonly InterfaceRepository<Hospital> hospitalRepository;
        private readonly InterfaceRepository<Department> departmentRepository;
        private readonly InterfaceRepository<UserReservation> userReserveRepository;
        private readonly IHostingEnvironment hosting;

        public HospitalController(InterfaceRepository<Hospital> hospitalRepository,
                                  InterfaceRepository<Department> departmentRepository,
                                  InterfaceRepository<UserReservation> UserReserveRepository,
                                  IHostingEnvironment hosting)
        {
            this.hospitalRepository = hospitalRepository;
            this.departmentRepository = departmentRepository;
            this.userReserveRepository = UserReserveRepository;
            this.hosting = hosting;
        }
        // GET: HospitalController
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(hospitalRepository.List());
        }
        // GET: HospitalController/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            return View(hospitalRepository.Find(id));
        }
        [Authorize(Roles = "Admin")]
        deptHospitalViewModel getAllDepartment()
        {
            var viewModel = new deptHospitalViewModel
            {
                Departments = departmentRepository.List().ToList()
            };
            return viewModel;
        }
        /*************Get All User Reserve in hospital*****************/
        //get all user reserve in hospital
        [Authorize(Roles = "Admin")]
        public ActionResult GetAllUserReserve()
        {
            return View(userReserveRepository.List());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetUserGroupByHospital()
        {
            
            var hospital = userReserveRepository.List().GroupBy(g => g.Hospital.Hos_Name).Select(s => new HospitalViewModel { Hos_Name = s.Key, userResverations = s });
            return View(hospital);
        }
        /*****************add or delete and list by publiher********************/
        // get all user reserve in specafic hospital
        [Authorize(Roles = "HospitalAdmin")]
        public ActionResult GetUserByHospital()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var hospital = hospitalRepository.List().Where(u => u.UserId == userId).Select(a => a.Hos_Id).SingleOrDefault();
            var users = userReserveRepository.List().Where(a => a.Hos_Id == hospital);
            return View(users);
        }
        // get hospital that publisher create
        [Authorize(Roles = "HospitalAdmin")]
        public ActionResult GetHospitalByPublisher()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var hospital = hospitalRepository.List().Where(a => a.UserId == userId);
            return View(hospital);
        }
        [Authorize(Roles = "HospitalAdmin")]
        [NoDirectAccess]
        public ActionResult AddOrEditbyPublisher(int id = 0)
        {
            //هنا هو بيشوف لو الاى دى صفر يبقي هو بينشاء مستخدم لو مش بصفر يبقي بيعدل عليه
            if (id == 0)
            {
                return View(getAllDepartment());
            }
            else
            {
                var hospital = hospitalRepository.Find(id);
                var deptId = hospital.Department == null ? 0 : hospital.Department.Dept_Id;
                var viewModel = new deptHospitalViewModel
                {
                    Hos_Id = hospital.Hos_Id,
                    Hos_Name = hospital.Hos_Name,
                    Hos_Location = hospital.Hos_Location,
                    Hos_Incubators = hospital.Hos_Incubators,
                    Hos_Phone = hospital.Hos_Phone,
                    Hos_Image = hospital.Hos_Image,
                    hos_pic = hospital.hos_pic,
                    DayPrice = hospital.DayPrice,
                    dateCreate = hospital.dateCreate,
                    Dept_Id = deptId,
                    UserId = hospital.UserId,
                    Departments = departmentRepository.List().ToList()
                };
                return View(viewModel);
            }


        }
        //////////////
        // POST: BookController/Add or Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEditbyPublisher(int id, deptHospitalViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                if (id == 0)
                {
                    var hospitalname = hospitalRepository.List().Select(a => a.Hos_Name);
                    if (hospitalname.Contains(model.Hos_Name))
                    {
                        ModelState.AddModelError("Hos_Name", $"Hospital {model.Hos_Name} is already in use.");
                        return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEditbyPublisher", getAllDepartment()) });
                    }
                    else
                    {
                        //to upload photo
                        //string fileName = string.Empty;
                        //if (model.File != null)
                        //{
                        //    string uploads = Path.Combine(hosting.WebRootPath, "images/Hospital");
                        //    fileName = model.File.FileName;
                        //    string fullPath = Path.Combine(uploads, fileName);
                        //    model.File.CopyTo(new FileStream(fullPath, FileMode.Create));
                            
                        //}
                        //اجيب المدينه من الجدول بتاعها
                        var department = departmentRepository.Find(model.Dept_Id);
                        var hospital = new Hospital
                        {
                            Hos_Name = model.Hos_Name,
                            Hos_Incubators = model.Hos_Incubators,
                            Hos_Phone = model.Hos_Phone,
                            //Hos_Image = fileName,
                            Hos_Location = model.Hos_Location,
                            dateCreate = DateTime.Now,
                            DayPrice = model.DayPrice,
                            UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                            Department = department

                        };
                        //take profile img and insert to DB
                        if (Request.Form.Files.Count > 0)
                        {
                            var file = Request.Form.Files.FirstOrDefault();
                            //check file size and extention
                            using (var dataStream = new MemoryStream())
                            {
                                file.CopyTo(dataStream);
                                hospital.hos_pic = dataStream.ToArray();
                            }
                        }
                        hospitalRepository.Add(hospital);

                    }
                      
                }
                else
                {
                    ////to upload photo
                    //string fileName = string.Empty;
                    //if (model.File != null)
                    //{
                    //    string uploads = Path.Combine(hosting.WebRootPath, "images/Hospital");
                    //    fileName = model.File.FileName;
                    //    string fullPath = Path.Combine(uploads, fileName);
                    //    //delete old path
                    //    string oldFileName = hospitalRepository.Find(model.Hos_Id).Hos_Image;
                    //    string fullOldPath = Path.Combine(uploads, oldFileName);
                    //    if (fullOldPath != fullPath)
                    //    {
                    //        System.IO.File.Delete(fullOldPath);
                    //        //save new file
                    //        model.File.CopyTo(new FileStream(fullPath, FileMode.Create));

                    //    }

                    //}
                    ////////////////////////////////
                    var department = departmentRepository.Find(model.Dept_Id);
                    var hospital = new Hospital
                    {
                        Hos_Id = model.Hos_Id,
                        Hos_Name = model.Hos_Name,
                        Hos_Location = model.Hos_Location,
                        Hos_Incubators = model.Hos_Incubators,
                        Hos_Phone = model.Hos_Phone,
                        //Hos_Image = fileName,
                        DayPrice = model.DayPrice,
                        dateCreate = DateTime.Now,
                        hos_pic = model.hos_pic,
                        UserId = model.UserId,
                        Department = department
                    };
                    //take profile img and insert to DB
                    if (Request.Form.Files.Count > 0)
                    {
                        var file = Request.Form.Files.FirstOrDefault();
                        //check file size and extention
                        using (var dataStream = new MemoryStream())
                        {

graduationProject/Views/Hospital/AddOrEdit.cshtml
@model deptHospitalViewModel

@{
    ViewData["Title"] = "Add Or Edit";
    Layout = null;
}
<style>
    .modal-dialog {
        max-width: 840px;
    }

    .modal-content {
        min-width: 100%;
        padding-left: 25px;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Hos_Id" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Hos_Id" class="form-control" />
                    <input type="hidden" asp-for="UserId" class="form-control" />
                    <input type="hidden" asp-for="hos_pic" class="form-control" />

                    <div class="form-group">
                        <label asp-for="Hos_Name" class="control-label"></label>
                        <input asp-for="Hos_Name" class="form-control" />
                        <span asp-validation-for="Hos_Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Hos_Location" class="control-label"></label>
                        <input asp-for="Hos_Location" class="form-control" />
                        <span asp-validation-for="Hos_Location" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Hos_Phone" class="control-label"></label>
                                <input asp-for="Hos_Phone" class="form-control" />
                                <span asp-validation-for="Hos_Phone" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Departments" class="control-label "></label>
                                <select asp-for="Dept_Id" class="form-control" asp-items="@(new SelectList(Model.Departments, "Dept_Id", "Dept_Name"))">
                                    <option value="" disabled selected>Choose your country</option>
                                </select>
                                <span asp-validation-for="Dept_Id" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Hos_Incubators" class="control-label"></label>
                                <input asp-for="Hos_Incubators" class="form-control" />
                                <span asp-validation-for="Hos_Incubators" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="DayPrice" class="control-label"></label>
                                <input asp-for="DayPrice" class="form-control" />
                                <span asp-validation-for="DayPrice" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="File" class="w-100">اختر صورة</label>
                        @if (Model.hos_pic != null)
                        {
                            <img style="width: 230px; height: 195px" class="img-thumbnail profile-Image" id="profileImg" alt="profile" src="data:image/*;base64,@(Convert.ToBase64String(Model.hos_pic))"/>
                        }
                        else
                        {
                            <img style="width: 230px; height: 195px" class="img-thumbnail profile-Image" id="profileImg" alt="profile" src="~/images/25-258285_free-icons-png-search-user-icon-png.png" />
                        }
                        <div class="custom-file mt-2">
                            <input name="File" type="file"
                                   accept="image/*"
                                   asp-for="hos_pic"
                                   class="custom-file-input"
                                   onchange="document.getElementById('profileImg').src = window.URL.createObjectURL(this.files[0])" />
                            <label class="custom-file-label" asp-for="hos_pic">اختار صورة</label>
                            <span asp-validation-for="hos_pic" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />-->
}

graduationProject/Views/Hospital/Details.cshtml
@model graduationProject.Models.Hospital

@{
    ViewData["Title"] = "Details hospital";
    ViewBag.hospitallist = "active";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card" style="padding: 20px; padding-left: 60px;">
                    <div class="header">
                        <h1>تفاصيل </h1>
                        <h4>عرض بيانات المستشفي</h4>
                    </div>
                    <div class="content">
                        <div class="row">
                            <div class="col-md-6">
                                <dl class="row">
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.Hos_Name)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.Hos_Name)
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.Hos_Incubators)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.Hos_Incubators)
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.DayPrice)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.DayPrice)
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.Hos_Location)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.Hos_Location)
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.Hos_Phone)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.Hos_Phone)
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.dateCreate)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.dateCreate)
                                    </dd>
                                    <dt class="col-sm-4">
                                        @Html.DisplayNameFor(model => model.Department)
                                    </dt>
                                    <dd class="col-sm-8">
                                        @Html.DisplayFor(model => model.Department.Dept_Name)
                                    </dd>
                                </dl>
                            </div>
                            <div class="col-md-6">
                                <dl class="row">
                                    <dt class="col-sm-8">
                                        @Html.DisplayNameFor(model => model.hos_pic)
                                        @if (@Model.hos_pic != null)
                                        {
                                            <img style="width: 230px; height: 195px" class="img-thumbnail" src="~/images/Hospital/@Model.Hos_Image" />
                                        }
                                        else
                                        {
                                            <img style="width: 230px; height: 195px" class="img-thumbnail" src="~/images/25-258285_free-icons-png-search-user-icon-png.png" />
                                        }
                                    </dt>
                                </dl>
                            </div>
                        </div>
                        <div class="text-center">
                            <a onclick="showInPopup('@Url.Action("AddOrEdit","Hospital",new {id=Model.Hos_Id},Context.Request.Scheme)','Edit')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i>Edit</a>
                            <a class="btn btn-outline-primary" asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

graduationProject/Views/Hospital/GetAllUserReserve.cshtml
@model IEnumerable<graduationProject.Models.UserReservation>

@{
    ViewData["Title"] = "User Reservations";
    ViewBag.usersreserve = "active";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        DataTable
                    </div>
                    <div class="card-body">
                        <div class="header">
                            <h1>User Reservation</h1>
                        </div>
                        <table id="datatablesSimple" class="table table-striped mt-4">
                            <thead>
                                <tr class="bg-primary text-white">
                                    <th>
                                        @Html.DisplayNameFor(model => model.User.FirstName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.User.LastName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Hospital.Hos_Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Res_Date)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Num_Incubators)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tfoot></tfoot>
                            <tbody >
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.User.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.User.LastName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Hospital.Hos_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Res_Date)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Num_Incubators)
                                    </td>
                                    <td>

                                        <a href="javascript:;" class="btn btn-danger js-delete" data-id="@item.Id"><i class="far fa-trash-alt"></i>Cancel Reservation</a>
                                        
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    
}

graduationProject/Views/Hospital/Index.cshtml
@model IEnumerable<graduationProject.Models.Hospital>
@{
    ViewData["Title"] = "Hospitals";
    ViewBag.hospitallist = "active";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        DataTable Example
                    </div>
                    <div class="card-body">
                        <div class="create-edit text-end">
                            <a onclick="showInPopup('@Url.Action("AddOrEdit", "Hospital", null, Context.Request.Scheme)', 'Create New')" class="btn btn-primary" id="button1"><i class="far fa-plus-square"></i>Create New</a>
                        </div>
                        <div class="alert alert-success alert-dismissible fade show mt-4 d-none" id="alert" role="alert">
                            <strong>Success</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <table id="datatablesSimple" class="table table-striped mt-4">
                            <thead>
                                <tr class="bg-primary text-white">
                                    <th>
                                        @Html.DisplayNameFor(model => model.Hos_Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Department.Dept_Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Hos_Location)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Hos_Phone)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Hos_Incubators)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.DayPrice)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.hos_pic)
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tfoot>

                            </tfoot>
                            <tbody id="view-all">
                                @Html.Partial("_ViewAllHospital", Model)
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />

}

graduationProject/Views/Hospital/_ViewAllHospital.cshtml
@model IEnumerable<graduationProject.Models.Hospital>
@foreach (var item in Model)
{
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Department.Dept_Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Location)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Phone)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Incubators)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DayPrice)
    </td>

    <td>
        @if (item.hos_pic != null)
        {
            <img src="data:image/*;base64,@(Convert.ToBase64String(item.hos_pic))" style="width:64px;" class="img-thumbnail" />
        }

    </td>
    <td>
        <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Hos_Id">Details</a>
        <a onclick="showInPopup('@Url.Action("AddOrEdit","Hospital",new {id=item.Hos_Id},Context.Request.Scheme)','Edit')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i>Edit</a>
        <form asp-action="Delete" asp-route-id="@item.Hos_Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
            <input type="hidden" asp-for="@item.Hos_Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>


    </td>
</tr>
}

graduationProject/Views/Hospital/_ViewHospitalsbyPublisher.cshtml
@model IEnumerable<graduationProject.Models.Hospital>
@foreach (var item in Model)
{
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Department.Dept_Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Location)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Phone)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hos_Incubators)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DayPrice)
    </td>

    <td>
        @if (item.hos_pic != null)
        {
            <img src="data:image/*;base64,@(Convert.ToBase64String(item.hos_pic))" style="width:64px;" class="img-thumbnail" />
        }

    </td>

    <td>
        <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Hos_Id">Details</a>
        <a onclick="showInPopup('@Url.Action("AddOrEditbyPublisher","Hospital",new {id=item.Hos_Id},Context.Request.Scheme)','Edit')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i>Edit</a>
        <form asp-action="DeletebyPublisher" asp-route-id="@item.Hos_Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
            <input type="hidden" asp-for="@item.Hos_Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>


    </td>
</tr>
}