graduationProject/Models/OxygenTube.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace graduationProject.Models
{
    public partial class OxygenTube
    {
        [Key]
        public int OxgnId { get; set; }
        [Display(Name = "النوع")]
        public string OxgnType { get; set; }
        [Display(Name = "العدد")]
        public int? OxgnAmount { get; set; }
        [Display(Name = "السعر")]
        public int? OxgnCost { get; set; }
        [Display(Name = "المحمول")]
        public string OxgnPhone { get; set; }
        [Display(Name = "الموقع")]
        public string OxgnLocation { get; set; }
        [Display(Name = "الوصف")]
        public string OxgnDescription { get; set; }

        public DateTime dateCreate { get; set; }

        [ForeignKey("Department")]
        public int Dept_Id { get; set; }

        public Department Department { get; set; }

        [ForeignKey("User")]
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
    }
}

graduationProject/Controllers/OxygenTubeController.cs
using graduationProject.Models;
using graduationProject.Repositories;
using graduationProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static graduationProject.Helper;

namespace graduationProject.Controllers
{
    public class OxygenTubeController : Controller
    {
        private readonly InterfaceRepository<OxygenTube> oxygenTubeRepository;
        private readonly InterfaceRepository<Department> departmentRepository;
        private readonly InterfaceRepository<UserReservationOxegin> userReserveRepository;
       

        public OxygenTubeController(InterfaceRepository<OxygenTube> oxygenTubeRepository,
                                  InterfaceRepository<Department> departmentRepository,
                                  InterfaceRepository<UserReservationOxegin> UserReserveRepository
                                 )
        {
            this.oxygenTubeRepository = oxygenTubeRepository;
            this.departmentRepository = departmentRepository;
            this.userReserveRepository = UserReserveRepository;
           
        }
        // GET: HospitalController
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(oxygenTubeRepository.List());
        }
        /**********department**********/
        deptTubeViewModel getAllDepartment()
        {
            var viewModel = new deptTubeViewModel
            {
                Departments = departmentRepository.List().ToList()
            };
            return viewModel;
        }
        /*************Get All User Reserve in hospital*****************/
        //get all user reserve in hospital
        [Authorize(Roles = "Admin")]
        public ActionResult GetAllUserReserve()
        {
            return View(userReserveRepository.List());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetUserGroupByTube()
        {
            
            var Tubes = userReserveRepository.List().GroupBy(g => g.OxygenTube.OxgnType).Select(s => new TubesViewModel { OxgnType = s.Key, UserReservationOxegin = s });
            return View(Tubes);
        }
        /*****************add or delete and list by publiher********************/
        // get all user reserve in specafic hospital
        [Authorize(Roles = "OxginAdmin")]
        public ActionResult GetUserByTube()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var tube = oxygenTubeRepository.List().Where(u => u.UserId == userId).Select(a => a.OxgnId).SingleOrDefault();
            var users = userReserveRepository.List().Where(a => a.Oxygen_Id == tube);
            return View(users);
        }
        // get hospital that publisher create
        [Authorize(Roles = "OxginAdmin")]
        public ActionResult GetTubeByPublisher()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var tube = oxygenTubeRepository.List().Where(a => a.UserId == userId);
            return View(tube);
        }
        [Authorize(Roles = "OxginAdmin")]
        //[NoDirectAccess]
        public ActionResult AddOrEditbyPublisher(int id = 0)
        {
            //هنا هو بيشوف لو الاى دى صفر يبقي هو بينشاء مستخدم لو مش بصفر يبقي بيعدل عليه
            if (id == 0)
            {
                return View(getAllDepartment());
            }
            else
            {
                var tube = oxygenTubeRepository.Find(id);
                var deptId = tube.Department == null ? 0 : tube.Department.Dept_Id;
                var viewModel = new deptTubeViewModel
                {
                    OxgnId= tube.OxgnId,
                    OxgnType = tube.OxgnType,
                    OxgnAmount = tube.OxgnAmount,
                    OxgnCost = tube.OxgnCost,
                    OxgnDescription = tube.OxgnDescription,
                    OxgnLocation = tube.OxgnLocation,
                    OxgnPhone = tube.OxgnPhone,
                    dateCreate = tube.dateCreate,
                    Dept_Id = deptId,
                    UserId = tube.UserId,
                    Departments = departmentRepository.List().ToList()
                };
                return View(viewModel);
            }


        }
        //////////////
        // POST: BookController/Add or Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEditbyPublisher(int id, deptTubeViewModel model)
        {
            if (ModelState.IsValid)
            {

                if (id == 0)
                {
                    var hospitalname = oxygenTubeRepository.List().Select(a => a.OxgnType);
                    if (hospitalname.Contains(model.OxgnType))
                    {
                        ModelState.AddModelError("OxgnType", $"OxgnType {model.OxgnType} is already in use.");
                        return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEditbyPublisher", getAllDepartment()) });
                    }
                    else
                    {
                        //اجيب المدينه من الجدول بتاعها
                        var department = departmentRepository.Find(model.Dept_Id);
                        var oxygenTube = new OxygenTube
                        {
                            OxgnType = model.OxgnType,
                            OxgnPhone = model.OxgnPhone,
                            OxgnLocation= model.OxgnLocation,
                            OxgnDescription = model.OxgnDescription,
                            OxgnAmount = model.OxgnAmount,
                            OxgnCost = model.OxgnCost,
                            dateCreate = DateTime.Now,
                            UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier),
                            Department = department

                        };
                        oxygenTubeRepository.Add(oxygenTube);

                    }

                }
                else
                {
                    //to upload photo
                    
                    ////////////////////////////////
                    var department = departmentRepository.Find(model.Dept_Id);
                    var oxygenTube = new OxygenTube
                    {
                        OxgnType = model.OxgnType,
                        OxgnPhone = model.OxgnPhone,
                        OxgnLocation = model.OxgnLocation,
                        OxgnDescription = model.OxgnDescription,
                        OxgnAmount = model.OxgnAmount,
                        OxgnCost = model.OxgnCost,
                        dateCreate = DateTime.Now,
                        UserId = model.UserId,
                        Department = department
                    };
                    oxygenTubeRepository.Update(model.OxgnId, oxygenTube);
                }
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var tubes = oxygenTubeRepository.List().Where(a => a.UserId == userId);
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewTubesbyPublisher", tubes) });
            }
            else
            {
                ////to handle error message in validation span
                ModelState.AddModelError("", "You have to fill all the required fields");
                return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEditbyPublisher", getAllDepartment()) });
            }

        }

        // جزء الحذف
        [Authorize(Roles = "OxginAdmin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletebyPublisher(int id)
        {
            try
            {
                oxygenTubeRepository.Delete(id);
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var hospitals = oxygenTubeRepository.List().Where(a => a.UserId == userId);
                return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewTubesbyPublisher", hospitals) });
            }
            catch
            {
                return NotFound();
            }


        }
        /****************end publisher section*******************/
        /****************admin[ add edit delete]*******************/
        ///عشان مفيش حد مباشر ينادى اللينك بتاعها 
        [Authorize(Roles = "Admin")]
        [NoDirectAccess]
        public ActionResult AddOrEdit(int id = 0)
        {
            //هنا هو بيشوف لو الاى دى صفر يبقي هو بينشاء مستخدم لو مش بصفر يبقي بيعدل عليه
            if (id == 0)
            {
                return View(getAllDepartment());
            }
            else
            {
                var tube = oxygenTubeRepository.Find(id);
                var deptId = tube.Department == null ? 0 : tube.Department.Dept_Id;
                var viewModel = new deptTubeViewModel
                {
                    OxgnId = tube.OxgnId,
                    OxgnType = tube.OxgnType,
                    OxgnAmount = tube.OxgnAmount,
                    OxgnCost = tube.OxgnCost,
                    OxgnDescription = tube.OxgnDescription,
                    OxgnLocation = tube.OxgnLocation,
                    OxgnPhone = tube.OxgnPhone,
                    dateCreate = tube.dateCreate,
                    Dept_Id = deptId,
                    UserId = tube.UserId,
                    Departments = departmentRepository.List().ToList()
                };
                return View(viewModel);
            }


        }
        //////////////
        // POST: BookController/Add or Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(int id, deptTubeViewModel model)
        {

graduationProject/Views/OxygenTube/AddOrEdit.cshtml
@model graduationProject.ViewModels.deptTubeViewModel
@{
    ViewData["Title"] = "Add Or Edit";
    Layout = null;
}
<style>
    .modal-dialog {
        max-width: 840px;
    }

    .modal-content {
        min-width: 100%;
        padding-left: 25px;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.OxgnId" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div class="row">
                <div class="col-md-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="OxgnId" class="form-control" />
                    <input type="hidden" asp-for="UserId" class="form-control" />
                    <div class="form-group">
                        <label asp-for="OxgnType" class="control-label"></label>
                        <input asp-for="OxgnType" class="form-control" />
                        <span asp-validation-for="OxgnType" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnAmount" class="control-label"></label>
                                <input asp-for="OxgnAmount" class="form-control" />
                                <span asp-validation-for="OxgnAmount" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnCost" class="control-label"></label>
                                <input asp-for="OxgnCost" class="form-control" />
                                <span asp-validation-for="OxgnCost" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnLocation" class="control-label"></label>
                                <input asp-for="OxgnLocation" class="form-control" />
                                <span asp-validation-for="OxgnLocation" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnDescription" class="control-label"></label>
                                <input asp-for="OxgnDescription" class="form-control" />
                                <span asp-validation-for="OxgnDescription" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Departments" class="control-label "></label>
                                <select asp-for="Dept_Id" class="form-control" asp-items="@(new SelectList(Model.Departments, "Dept_Id", "Dept_Name"))">
                                    <option value="" disabled selected>Choose your country</option>
                                </select>
                                <span asp-validation-for="Dept_Id" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnPhone" class="control-label"></label>
                                <input asp-for="OxgnPhone" class="form-control" />
                                <span asp-validation-for="OxgnPhone" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />-->
}

graduationProject/Views/OxygenTube/AddOrEditbyPublisher.cshtml
@model graduationProject.ViewModels.deptTubeViewModel
@{
    ViewData["Title"] = "Add Or Edit";
    Layout = null;
}
<style>
    .modal-dialog {
        max-width: 840px;
    }

    .modal-content {
        min-width: 100%;
        padding-left: 25px;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEditbyPublisher" asp-route-id="@Model.OxgnId" onsubmit="return jQueryAjaxPost(this);" autocomplete="off" >
            <div class="row">
                <div class="col-md-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="OxgnId" class="form-control" />
                    <input type="hidden" asp-for="UserId" class="form-control" />
                    <div class="form-group">
                        <label asp-for="OxgnType" class="control-label"></label>
                        <input asp-for="OxgnType" class="form-control" />
                        <span asp-validation-for="OxgnType" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnAmount" class="control-label"></label>
                                <input asp-for="OxgnAmount" class="form-control" />
                                <span asp-validation-for="OxgnAmount" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnCost" class="control-label"></label>
                                <input asp-for="OxgnCost" class="form-control" />
                                <span asp-validation-for="OxgnCost" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnLocation" class="control-label"></label>
                                <input asp-for="OxgnLocation" class="form-control" />
                                <span asp-validation-for="OxgnLocation" class="text-danger"></span>
                            </div>
                            
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnDescription" class="control-label"></label>
                                <input asp-for="OxgnDescription" class="form-control" />
                                <span asp-validation-for="OxgnDescription" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Departments" class="control-label "></label>
                                <select asp-for="Dept_Id" class="form-control" asp-items="@(new SelectList(Model.Departments, "Dept_Id", "Dept_Name"))">
                                    <option value="" disabled selected>Choose your country</option>
                                </select>
                                <span asp-validation-for="Dept_Id" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="OxgnPhone" class="control-label"></label>
                                <input asp-for="OxgnPhone" class="form-control" />
                                <span asp-validation-for="OxgnPhone" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@section Scripts {

    <partial name="_ValidationScriptsPartial" />-->
}

graduationProject/Views/OxygenTube/GetAllUserReserve.cshtml
@model IEnumerable<graduationProject.Models.UserReservationOxegin>

@{
    ViewData["Title"] = "GetAllUserReserve";
    ViewBag.usersreservetubes = "active";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        DataTable
                    </div>
                    <div class="card-body">
                        <div class="header">
                            <h1>User Reservation</h1>
                        </div>
                        <table id="datatablesSimple" class="table table-striped mt-4">
                            <thead>
                                <tr class="bg-primary text-white">
                                    <th>
                                        @Html.DisplayNameFor(model => model.User.FirstName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.User.LastName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxygenTube.OxgnType)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Res_Date)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Num_tubes)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tfoot></tfoot>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.User.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.User.LastName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.OxygenTube.OxgnType)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Res_Date)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Num_tubes)
                                        </td>
                                        <td>

                                            <a href="javascript:;" class="btn btn-danger js-delete" data-id="@item.Id"><i class="far fa-trash-alt"></i>Cancel Reservation</a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

graduationProject/Views/OxygenTube/Index.cshtml
@model IEnumerable<graduationProject.Models.OxygenTube>
@{
    ViewData["Title"] = "Oxegin Tubes";
    ViewBag.Oxeginlist = "active";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        DataTable Example
                    </div>
                    <div class="card-body">
                        <div class="create-edit text-end">
                            <a onclick="showInPopup('@Url.Action("AddOrEdit", "OxygenTube", null, Context.Request.Scheme)', 'Create New')" class="btn btn-primary" id="button1"><i class="far fa-plus-square"></i>Create New</a>
                        </div>
                        <div class="alert alert-success alert-dismissible fade show mt-4 d-none" id="alert" role="alert">
                            <strong>Success</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <table id="datatablesSimple" class="table table-striped mt-4">
                            <thead>
                                <tr class="bg-primary text-white">
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxgnType)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxgnAmount)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxgnCost)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxgnPhone)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxgnLocation)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.OxgnDescription)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Department)
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tfoot>

                            </tfoot>
                            <tbody id="view-all">
                                @Html.Partial("_ViewAllTubes", Model)
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />

}

graduationProject/Views/OxygenTube/_ViewAllTubes.cshtml
@model IEnumerable<graduationProject.Models.OxygenTube>
@foreach (var item in Model)
{

    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OxgnType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OxgnAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OxgnCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OxgnPhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OxgnLocation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OxgnDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.Dept_Id)
        </td>
        <td>
            <a onclick="showInPopup('@Url.Action("AddOrEdit","OxygenTube",new {id=item.OxgnId},Context.Request.Scheme)','Edit')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i>Edit</a>
            <form asp-action="Delete" asp-route-id="@item.OxgnId" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                <input type="hidden" asp-for="@item.OxgnId" />
                <input type="submit" value="Delete" class="btn btn-danger" />
            </form>


        </td>
    </tr>
    }

graduationProject/Views/OxygenTube/_ViewTubesbyPublisher.cshtml
@model IEnumerable<graduationProject.Models.OxygenTube>
@foreach (var item in Model)
{
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.OxgnType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OxgnAmount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OxgnCost)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OxgnPhone)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OxgnLocation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.OxgnDescription)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Department.Dept_Name)
    </td>

    <td>
        <a onclick="showInPopup('@Url.Action("AddOrEditbyPublisher","OxygenTube",new {id=item.OxgnId},Context.Request.Scheme)','Edit')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i>Edit</a>
        <form asp-action="DeletebyPublisher" asp-route-id="@item.OxgnId" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
            <input type="hidden" asp-for="@item.OxgnId" />
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>


    </td>
</tr>
}